### ISSUE TITLE
setup.py vulnerable to shell command injection

### ISSUE THREAD

**Issue by semiconductor12** [naibaf7/PyGreentea#2]
Script _setup.py_ is vulnerable to shell command injection since it uses _os.system()_. This function and _os.popen()_ are deprecated in Python nowadays. It is recommended to use the subprocess module instead. The first argument _path_ in clone_malis() and clone_caffe() would be vulnerable to shell command injection (see github.com/python-pillow/Pillow/issues/1520) if the string argument would terminate the git clone command early and add additional commands (e.g. os.system('git clone <url> path;xterm')). This would first execute _git clone_ and then execute _xterm_. It is therefore recommended to change:

os.system('git clone <url> %s' % path) 

to 

subprocess.call(['git', 'clone', '<url>', path])

**Comment by naibaf7** [comment]
Thanks! Good to know.
The setup.py is a temporary solution to demonstrate the dependencies only anyways. We are looking for a better solution.

**Comment by semiconductor12** [comment]
I just wanted to shortly raise this issue. Sure, I see that this is a temporary solution for you and it is maybe not in the focus of what you are actually doing. I only recently learned about this shell command injection issues (see github.com/theregrunner) and that it used to be a problem in many open-source software projects. I also got the impression, that it is getting fixed in many cases – especially when a package belongs to a major Linux distribution. I looked into some trending Python packages at github where many people contribute to and it turns out that non of these Python packages use _os.system()_ and _os.popen()_ anymore. Just to let you know, It's up to you now. Thanks for your response.

**Comment by jakirkham** [comment]
It is tricky to handle non-Python dependencies and I definitely appreciate that you have documented them in some form so others know what they are. Though this will need to get changed somehow, I think that we can all agree on, but I am not as worried about that right now.

_Some_ of these dependencies are in [conda-forge](https://conda-forge.github.io/). Eventually I would like to get nearly _all_ of them. However, I think there will need to be some more decisions made at conda-forge and changes to [conda](http://conda.pydata.org/docs/) before that will be practical. Though having an intermediate solution (another repo with some conda recipes and packages on [anaconda.org](http://anaconda.org/)) should still be achievable. This would at least provide a better method of packaging and installation.

Though I do have some questions about the dependencies here and may come back to ask more in the future. It appears that you are installing two BLASes namely ATLAS and OpenBLAS. Is there a reason for that or could you just as easily use one of them? Is this simply due to how caffe is doing things?

**Comment by naibaf7** [comment]
@jakirkham 
Using one BLAS is enough. It's up to the user to configure the Caffe makefile to use one or the other. When running in GPU mode, the CPU blas is (almost) never used.

**Comment by jakirkham** [comment]
> Using one BLAS is enough.

Great, thanks for the clarification.

> It's up to the user to configure the Caffe makefile to use one or the other.

Ok, I'll take a closer look at that once I have nailed down a few more dependencies.

> When running in GPU mode, the CPU blas is (almost) never used.

Right. Meaning you are using ViennaCL or something else?

**Comment by naibaf7** [comment]
@jakirkham 
Yes, GPU BLAS is cuBLAS on CUDA backend and clBLAS or ViennaCL on OpenCL backend.

**Comment by jakirkham** [comment]
Great. Thanks for clarifying.

**Comment by naibaf7** [comment]
This has been resolved.
